_target_: src.models.baseline_module_edc.MultiSlopeEstimation

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 4

mono_weight: 0.2

component:
  _target_: src.models.components.transformer.Transformer
  d_model: 128
  nhead: 4
  dim_feedforward: 256
  num_layers: 1
  dropout: 0.2
  out_features: 700 # corresponds to lat size
  state: null
  front_end:
    _target_: src.models.components.cnn.CNNEncoder
    in_channels: 1
    channels: 4
    multipliers: [1, 2, 2, 2, 2]
    kernel_sizes: [[1, 11], [1, 11], [3, 7], [3, 7]]
    strides: [[1, 1], [1, 1], [1, 1], [1, 1]]
    factors: [[1, 1], [1, 2], [1, 2], [2, 2]]
    pads: [[0, 0], [0, 0], [0, 0], [0, 0]]
    num_blocks: [1, 1, 1, 1]
    ch_matching: null

t60_estimator:
  cfg: model/baseline_t60
  state: logs/baseline_t60/tensorboard/version_0/states.pkl